// <auto-generated />
using DemoSemiStaticContent.AspNetCore.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoSemiStaticContent.AspNetCore.Mvc.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20240724114543_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Olbrasoft.SemiStaticContent.SemiStaticContentItem", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("StaticContentItems");

                    b.HasData(
                        new
                        {
                            Key = "welcome",
                            Text = "# Welcome"
                        },
                        new
                        {
                            Key = "privacy",
                            Text = "This is my _privacy policy_."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
