// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Olbrasoft.DemoSemiStaticContent.EntityFrameworkCore.AspNetCore.Mvc.Data.EntityFrameworkCore;

#nullable disable

namespace Olbrasoft.DemoSemiStaticContent.EntityFrameworkCore.AspNetCore.Mvc.Migrations
{
    [DbContext(typeof(DemoSemiStaticContentContext))]
    partial class DemoSemiStaticContentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Olbrasoft.SemiStaticContent.SemiStaticContentItem", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SemiStaticContentItems");

                    b.HasData(
                        new
                        {
                            Key = "welcome",
                            Text = "# Welcome"
                        },
                        new
                        {
                            Key = "privacy",
                            Text = "This is my _privacy policy_."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
